import {
  Merge as Merge2,
  Scissors,
  Zap,
  ImagePlus,
  Droplets,
  Eye,
  FileSignature,
  Shield,
  RotateCw,
  Images,
  FileText,
  Lock,
  Unlock,
  Copy,
  Stamp,
  Grid3x3,
  Layers,
  Minimize,
  Type,
  Code,
  BarChart3,
  FileJson,
  Database,
  Upload,
  Bookmark,
  BookOpen,
  Layers2,
  Settings,
  AlertCircle,
  Paperclip,
  Trash2,
  Edit3,
  Eraser,
  Crop,
  Repeat,
  Plus,
  X,
} from "lucide-react"

export interface Tool {
  id: string
  name: string
  description: string
  href: string
  icon: any
  category: "conversion" | "compress" | "security" | "edit" | "extract" | "merge" | "organize" | "enhance"
  comingSoon?: boolean
}

export const TOOLS: Tool[] = [
  // MERGE & COMBINE (5 tools)
  {
    id: "merge",
    name: "Merge PDF",
    description: "Combine multiple PDFs into one single document.",
    href: "/tools/merge",
    icon: Merge2,
    category: "merge",
  },
  {
    id: "combine-multiple",
    name: "Combine Multiple Files",
    description: "Merge PDFs with specific page ranges and custom ordering.",
    href: "/tools/combine-multiple",
    icon: Layers,
    category: "merge",
  },
  {
    id: "append-pdf",
    name: "Append PDF",
    description: "Add pages from one PDF to the end of another.",
    href: "/tools/append-pdf",
    icon: Plus,
    category: "merge",
  },
  {
    id: "insert-pdf",
    name: "Insert PDF Pages",
    description: "Insert PDF pages at specific positions in another document.",
    href: "/tools/insert-pdf",
    icon: Paperclip,
    category: "merge",
  },
  {
    id: "shuffle-merge",
    name: "Shuffle & Merge",
    description: "Merge and interleave pages from multiple PDFs.",
    href: "/tools/shuffle-merge",
    icon: Repeat,
    category: "merge",
  },

  // EDIT & MANIPULATE (8 tools)
  {
    id: "split",
    name: "Split PDF",
    description: "Extract specific pages or split PDFs into separate files.",
    href: "/tools/split",
    icon: Scissors,
    category: "edit",
  },
  {
    id: "rotate",
    name: "Rotate PDF",
    description: "Rotate pages and adjust PDF orientation.",
    href: "/tools/rotate",
    icon: RotateCw,
    category: "edit",
  },
  {
    id: "crop",
    name: "Crop PDF",
    description: "Crop and remove margins from PDF pages.",
    href: "/tools/crop",
    icon: Crop,
    category: "edit",
  },
  {
    id: "delete-pages",
    name: "Delete Pages",
    description: "Remove unwanted pages from your PDF.",
    href: "/tools/delete-pages",
    icon: Trash2,
    category: "edit",
  },
  {
    id: "extract-pages",
    name: "Extract Pages",
    description: "Extract specific page ranges into a new PDF.",
    href: "/tools/extract-pages",
    icon: Copy,
    category: "edit",
  },
  {
    id: "reorder-pages",
    name: "Reorder Pages",
    description: "Reorganize PDF pages in any order you want.",
    href: "/tools/reorder-pages",
    icon: Grid3x3,
    category: "edit",
  },
  {
    id: "duplicate-pages",
    name: "Duplicate Pages",
    description: "Duplicate specific pages within your PDF.",
    href: "/tools/duplicate-pages",
    icon: Copy,
    category: "edit",
  },
  {
    id: "blank-pages",
    name: "Add Blank Pages",
    description: "Insert blank pages at specific positions in PDFs.",
    href: "/tools/blank-pages",
    icon: Plus,
    category: "edit",
  },

  // COMPRESS & OPTIMIZE (5 tools)
  {
    id: "compress",
    name: "Compress PDF",
    description: "Reduce file size while maintaining quality.",
    href: "/tools/compress",
    icon: Zap,
    category: "compress",
  },
  {
    id: "optimize-pdf",
    name: "Optimize PDF",
    description: "Optimize PDFs for web viewing with better compression.",
    href: "/tools/optimize-pdf",
    icon: Settings,
    category: "compress",
  },
  {
    id: "reduce-size",
    name: "Reduce Size",
    description: "Aggressively reduce PDF file size.",
    href: "/tools/reduce-size",
    icon: Minimize,
    category: "compress",
  },
  {
    id: "compress-images",
    name: "Compress Images in PDF",
    description: "Compress embedded images while keeping quality.",
    href: "/tools/compress-images",
    icon: BarChart3,
    category: "compress",
  },
  {
    id: "remove-duplicates",
    name: "Remove Duplicate Images",
    description: "Detect and remove duplicate images from PDFs.",
    href: "/tools/remove-duplicates",
    icon: AlertCircle,
    category: "compress",
  },

  // CONVERSION (8 tools)
  {
    id: "convert",
    name: "Images to PDF",
    description: "Convert images to PDF or extract images from PDFs.",
    href: "/tools/convert",
    icon: ImagePlus,
    category: "conversion",
  },
  {
    id: "pdf-to-images",
    name: "PDF to Images",
    description: "Convert PDF pages to individual image files.",
    href: "/tools/pdf-to-images",
    icon: Images,
    category: "conversion",
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDFs to editable Word documents.",
    href: "/tools/pdf-to-word",
    icon: FileText,
    category: "conversion",
    comingSoon: true,
  },
  {
    id: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Extract tables from PDFs to Excel format.",
    href: "/tools/pdf-to-excel",
    icon: BarChart3,
    category: "conversion",
    comingSoon: true,
  },
  {
    id: "html-to-pdf",
    name: "HTML to PDF",
    description: "Convert HTML or web pages to PDF format.",
    href: "/tools/html-to-pdf",
    icon: Code,
    category: "conversion",
    comingSoon: true,
  },
  {
    id: "markdown-to-pdf",
    name: "Markdown to PDF",
    description: "Convert Markdown documents to professional PDFs.",
    href: "/tools/markdown-to-pdf",
    icon: FileJson,
    category: "conversion",
    comingSoon: true,
  },
  {
    id: "json-to-pdf",
    name: "JSON to PDF",
    description: "Convert JSON data to formatted PDF reports.",
    href: "/tools/json-to-pdf",
    icon: FileJson,
    category: "conversion",
    comingSoon: true,
  },
  {
    id: "text-to-pdf",
    name: "Text to PDF",
    description: "Convert plain text files to professional PDFs.",
    href: "/tools/text-to-pdf",
    icon: Type,
    category: "conversion",
    comingSoon: true,
  },

  // WATERMARK & ANNOTATE (4 tools)
  {
    id: "watermark",
    name: "Add Watermark",
    description: "Add text or image watermarks to your PDFs.",
    href: "/tools/watermark",
    icon: Droplets,
    category: "enhance",
  },
  {
    id: "add-stamp",
    name: "Add Stamp",
    description: "Apply stamps like 'Approved', 'Draft', etc.",
    href: "/tools/add-stamp",
    icon: Stamp,
    category: "enhance",
  },
  {
    id: "add-header-footer",
    name: "Add Header & Footer",
    description: "Add custom headers and footers to all pages.",
    href: "/tools/add-header-footer",
    icon: Layers2,
    category: "enhance",
  },
  {
    id: "add-page-numbers",
    name: "Add Page Numbers",
    description: "Add page numbers with custom formatting.",
    href: "/tools/add-page-numbers",
    icon: BookOpen,
    category: "enhance",
  },

  // EXTRACT & ANALYSIS (5 tools)
  {
    id: "ocr",
    name: "OCR - Extract Text",
    description: "Convert scanned PDFs to searchable text documents.",
    href: "/tools/ocr",
    icon: Eye,
    category: "extract",
  },
  {
    id: "extract-images",
    name: "Extract Images",
    description: "Extract all images from PDF files.",
    href: "/tools/extract-images",
    icon: Images,
    category: "extract",
  },
  {
    id: "extract-text",
    name: "Extract Text",
    description: "Extract all text content from PDF documents.",
    href: "/tools/extract-text",
    icon: FileText,
    category: "extract",
  },
  {
    id: "extract-metadata",
    name: "Extract Metadata",
    description: "Extract PDF metadata and document information.",
    href: "/tools/extract-metadata",
    icon: Database,
    category: "extract",
  },
  {
    id: "extract-tables",
    name: "Extract Tables",
    description: "Extract tables from PDFs to CSV or Excel.",
    href: "/tools/extract-tables",
    icon: BarChart3,
    category: "extract",
    comingSoon: true,
  },

  // SECURITY (6 tools)
  {
    id: "protect",
    name: "Protect PDF",
    description: "Add password protection and encryption to PDFs.",
    href: "/tools/protect",
    icon: Shield,
    category: "security",
  },
  {
    id: "unlock",
    name: "Unlock PDF",
    description: "Remove password protection from PDFs.",
    href: "/tools/unlock",
    icon: Unlock,
    category: "security",
  },
  {
    id: "sign",
    name: "Sign PDF",
    description: "Add digital signatures to your documents.",
    href: "/tools/sign",
    icon: FileSignature,
    category: "security",
    comingSoon: true,
  },
  {
    id: "remove-protection",
    name: "Remove Protection",
    description: "Remove copy and print restrictions.",
    href: "/tools/remove-protection",
    icon: Lock,
    category: "security",
  },
  {
    id: "encrypt",
    name: "Encrypt PDF",
    description: "Add strong encryption to PDFs.",
    href: "/tools/encrypt",
    icon: Shield,
    category: "security",
  },
  {
    id: "redact",
    name: "Redact PDF",
    description: "Hide sensitive content in PDFs permanently.",
    href: "/tools/redact",
    icon: Eraser,
    category: "security",
    comingSoon: true,
  },

  // ORGANIZE (4 tools)
  {
    id: "bookmark",
    name: "Add Bookmarks",
    description: "Add navigational bookmarks to PDF documents.",
    href: "/tools/bookmark",
    icon: Bookmark,
    category: "organize",
  },
  {
    id: "remove-metadata",
    name: "Remove Metadata",
    description: "Strip all metadata from PDF documents.",
    href: "/tools/remove-metadata",
    icon: X,
    category: "organize",
  },
  {
    id: "batch-rename",
    name: "Batch Rename",
    description: "Rename multiple PDFs with patterns and sequences.",
    href: "/tools/batch-rename",
    icon: Edit3,
    category: "organize",
    comingSoon: true,
  },
  {
    id: "batch-convert",
    name: "Batch Convert",
    description: "Convert multiple files to PDF in batch mode.",
    href: "/tools/batch-convert",
    icon: Upload,
    category: "organize",
    comingSoon: true,
  },
]
